keypoint_detectors:
    reference_pointcloud:
        sift_3d:
            min_scale: 0.015
            number_octaves: 4
            number_scales_per_octave: 8
            min_contrast: 0.0015
            sift3d_keypoints_cloud_publish_topic: 'reference_keypoints'
#        intrinsic_shape_signature_3d:
#            salient_radius: 0.14
#            non_max_radius: 0.08
#            normal_radius: 0.08
#            border_radius: 0.0
#            threshold21: 0.975
#            threshold32: 0.975
#            min_neighbors: 5
#            angle_threshold: 1.57
#            iss3d_keypoints_cloud_publish_topic: 'reference_keypoints'
    ambient_pointcloud:
        compute_keypoints_when_tracking_pose: false
        compute_keypoints_when_recovering_pose_tracking: false
        compute_keypoints_when_estimating_initial_pose: true
        sift_3d:
            min_scale: 0.015
            number_octaves: 4
            number_scales_per_octave: 8
            min_contrast: 0.0015
            sift3d_keypoints_cloud_publish_topic: 'ambient_keypoints'
#        intrinsic_shape_signature_3d:
#            salient_radius: 0.14
#            non_max_radius: 0.08
#            normal_radius: 0.08
#            border_radius: 0.0
#            threshold21: 0.975
#            threshold32: 0.975
#            min_neighbors: 5
#            angle_threshold: 1.57
#            iss3d_keypoints_cloud_publish_topic: 'ambient_keypoints'


initial_pose_estimators_matchers:
    feature_matchers:
        display_feature_matching: false
        save_descriptors_in_binary_format: true
        keypoint_descriptors:
            feature_descriptor_k_search: 0
            feature_descriptor_radius_search: 0.35
            fpfh:
                number_subdivisions_f1: 11
                number_subdivisions_f2: 11
                number_subdivisions_f3: 11
#            pfh:
#                use_internal_cache: true
#                maximum_cache_size: 33554432
#            shot:
#                lrf_radius: 0.5
#            shape_context_3d:
#                minimal_radius: 0.2
#                point_density_radius: 0.4
#            unique_shape_context:
#                minimal_radius: 0.1
#                point_density_radius: 0.2
#                local_radius: 2.5
#            esf:
#                feature_descriptor_radius_search: 0.25
        matchers:
            max_correspondence_distance: 0.25
            max_number_of_registration_iterations: 1337
            sample_consensus_initial_alignment_prerejective:
                convergence_time_limit_seconds: 3.0
                similarity_threshold: 0.6
                inlier_fraction: 0.65
                inlier_rmse: 0.35
                number_of_samples: 9
                correspondence_randomness: 3
#            sample_consensus_initial_alignment:
#                min_sample_distance: 0.5
#                number_of_samples: 3
#                correspondence_randomness: 15
    point_matchers:
        iterative_closest_point:
#        iterative_closest_point_2d:
#        iterative_closest_point_non_linear:
#        iterative_closest_point_generalized:
            convergence_time_limit_seconds: 2.0
            max_correspondence_distance: 10.0
            transformation_epsilon: 1e-6
            euclidean_fitness_epsilon: 1e-6
            max_number_of_registration_iterations: 350
            max_number_of_ransac_iterations: 350
            ransac_outlier_rejection_threshold: 0.05
            match_only_keypoints: false
            display_cloud_aligment: false
            maximum_number_of_displayed_correspondences: 0
            rotation_epsilon: 0.002
            correspondence_randomness: 50
            maximum_optimizer_iterations: 100
            use_reciprocal_correspondences: true
