/**\file registration_covariance_point_to_plane_3d.hpp
 * \brief Description...
 *
 * @version 1.0
 * @author Carlos Miguel Correia da Costa
 */

// >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>   <includes>   <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
#include <dynamic_robot_localization/registration_covariance_estimators/registration_covariance_point_to_plane_3d.h>
// >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>   </includes>  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

namespace dynamic_robot_localization {

// >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>   <imports>   <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
// >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>   </imports>  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

// =============================================================================  <public-section>  ============================================================================
// >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>   <constructors-destructor>   <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
// >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>   </constructors-destructor>  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

// >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>   <RegistrationCovariancePointToPlane3D-functions>   <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
template<typename PointT>
bool RegistrationCovariancePointToPlane3D<PointT>::computeRegistrationCovariance(const pcl::PointCloud<PointT>& reference_cloud_correspondences, const pcl::PointCloud<PointT>& ambient_cloud_orrespondences,
		const Eigen::Matrix4f& registration_corrections, Eigen::MatrixXd& covariance_out, double sensor_std_dev_noise) {
	if (reference_cloud_correspondences.empty() || ambient_cloud_orrespondences.empty()) {
		return false;
	}

	double correction_x = registration_corrections(0, 3);
	double correction_y = registration_corrections(1, 3);
	double correction_z = registration_corrections(2, 3);

	double correction_roll, correction_pitch, correction_yaw;
	math_utils::getRollPitchYawFromMatrix(registration_corrections, correction_roll, correction_pitch, correction_yaw);

	double cos_roll = cos(correction_roll);
	double sin_roll = sin(correction_roll);
	double cos_pitch = cos(correction_pitch);
	double sin_pitch = sin(correction_pitch);
	double cos_yaw = cos(correction_yaw);
	double sin_yaw = sin(correction_yaw);

	Eigen::MatrixXd d2J_dX2(6, 6);
	d2J_dX2 = Eigen::MatrixXd::Zero(6, 6);
	size_t ambient_cloud_orrespondences_size = ambient_cloud_orrespondences.points.size();

	for (size_t s = 0; s < ambient_cloud_orrespondences_size; ++s) {
		double pix = ambient_cloud_orrespondences[s].x;
		double piy = ambient_cloud_orrespondences[s].y;
		double piz = ambient_cloud_orrespondences[s].z;
		double qix = reference_cloud_correspondences[s].x;
		double qiy = reference_cloud_correspondences[s].y;
		double qiz = reference_cloud_correspondences[s].z;

		double nix = reference_cloud_correspondences[s].normal_x;
		double niy = reference_cloud_correspondences[s].normal_y;
		double niz = reference_cloud_correspondences[s].normal_z;

		double 	d2J_dx2 , d2J_dydx, d2J_dzdx, d2J_dadx, d2J_dbdx, d2J_dcdx,
				d2J_dxdy, d2J_dy2 , d2J_dzdy, d2J_dady, d2J_dbdy, d2J_dcdy,
				d2J_dxdz, d2J_dydz, d2J_dz2 , d2J_dadz, d2J_dbdz, d2J_dcdz,
				d2J_dxda, d2J_dyda, d2J_dzda, d2J_da2 , d2J_dbda, d2J_dcda,
				d2J_dxdb, d2J_dydb, d2J_dzdb, d2J_dadb, d2J_db2 , d2J_dcdb,
				d2J_dxdc, d2J_dydc, d2J_dzdc, d2J_dadc, d2J_dbdc, d2J_dc2;

		d2J_dx2 = 2 * pow(nix, 2);
		d2J_dy2 = 2 * pow(niy, 2);
		d2J_dz2 = 2 * pow(niz, 2);
		d2J_dydx = 2 * nix * niy;
		d2J_dxdy = 2 * nix * niy;
		d2J_dzdx = 2 * nix * niz;
		d2J_dxdz = 2 * nix * niz;
		d2J_dydz = 2 * niy * niz;
		d2J_dzdy = 2 * niy * niz;
		d2J_da2 = (niy * (piz * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) - piy * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + pix * cos_yaw * cos_pitch) - nix * (piy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - piz * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + pix * cos_pitch * sin_yaw)) * (2 * niy * (piz * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) - piy * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + pix * cos_yaw * cos_pitch) - 2 * nix * (piy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - piz * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + pix * cos_pitch * sin_yaw)) - (2 * nix * (piz * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) - piy * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + pix * cos_yaw * cos_pitch) + 2 * niy * (piy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - piz * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + pix * cos_pitch * sin_yaw)) * (nix * (correction_x - qix - piy * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + piz * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) + pix * cos_yaw * cos_pitch) + niy * (correction_y - qiy + piy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - piz * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + pix * cos_pitch * sin_yaw) + niz * (correction_z - qiz - pix * sin_pitch + piz * cos_pitch * cos_roll + piy * cos_pitch * sin_roll));
		d2J_db2 = (niy * (piz * cos_pitch * cos_roll * sin_yaw - pix * sin_yaw * sin_pitch + piy * cos_pitch * sin_yaw * sin_roll) - niz * (pix * cos_pitch + piz * cos_roll * sin_pitch + piy * sin_pitch * sin_roll) + nix * (piz * cos_yaw * cos_pitch * cos_roll - pix * cos_yaw * sin_pitch + piy * cos_yaw * cos_pitch * sin_roll)) * (2 * niy * (piz * cos_pitch * cos_roll * sin_yaw - pix * sin_yaw * sin_pitch + piy * cos_pitch * sin_yaw * sin_roll) - 2 * niz * (pix * cos_pitch + piz * cos_roll * sin_pitch + piy * sin_pitch * sin_roll) + 2 * nix * (piz * cos_yaw * cos_pitch * cos_roll - pix * cos_yaw * sin_pitch + piy * cos_yaw * cos_pitch * sin_roll)) - (2 * niy * (pix * cos_pitch * sin_yaw + piz * cos_roll * sin_yaw * sin_pitch + piy * sin_yaw * sin_pitch * sin_roll) + 2 * niz * (piz * cos_pitch * cos_roll - pix * sin_pitch + piy * cos_pitch * sin_roll) + 2 * nix * (pix * cos_yaw * cos_pitch + piz * cos_yaw * cos_roll * sin_pitch + piy * cos_yaw * sin_pitch * sin_roll)) * (nix * (correction_x - qix - piy * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + piz * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) + pix * cos_yaw * cos_pitch) + niy * (correction_y - qiy + piy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - piz * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + pix * cos_pitch * sin_yaw) + niz * (correction_z - qiz - pix * sin_pitch + piz * cos_pitch * cos_roll + piy * cos_pitch * sin_roll));
		d2J_dc2 = (nix * (piy * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) + piz * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll)) - niy * (piy * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + piz * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll)) + niz * (piy * cos_pitch * cos_roll - piz * cos_pitch * sin_roll)) * (2 * nix * (piy * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) + piz * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll)) - 2 * niy * (piy * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + piz * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll)) + 2 * niz * (piy * cos_pitch * cos_roll - piz * cos_pitch * sin_roll)) - (2 * niy * (piy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - piz * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch)) - 2 * nix * (piy * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) - piz * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch)) + 2 * niz * (piz * cos_pitch * cos_roll + piy * cos_pitch * sin_roll)) * (nix * (correction_x - qix - piy * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + piz * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) + pix * cos_yaw * cos_pitch) + niy * (correction_y - qiy + piy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - piz * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + pix * cos_pitch * sin_yaw) + niz * (correction_z - qiz - pix * sin_pitch + piz * cos_pitch * cos_roll + piy * cos_pitch * sin_roll));
		d2J_dxda = nix * (2 * niy * (piz * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) - piy * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + pix * cos_yaw * cos_pitch) - 2 * nix * (piy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - piz * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + pix * cos_pitch * sin_yaw));
		d2J_dadx = 2 * nix * (niy * (piz * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) - piy * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + pix * cos_yaw * cos_pitch) - nix * (piy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - piz * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + pix * cos_pitch * sin_yaw));
		d2J_dyda = niy * (2 * niy * (piz * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) - piy * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + pix * cos_yaw * cos_pitch) - 2 * nix * (piy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - piz * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + pix * cos_pitch * sin_yaw));
		d2J_dady = 2 * niy * (niy * (piz * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) - piy * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + pix * cos_yaw * cos_pitch) - nix * (piy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - piz * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + pix * cos_pitch * sin_yaw));
		d2J_dzda = niz * (2 * niy * (piz * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) - piy * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + pix * cos_yaw * cos_pitch) - 2 * nix * (piy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - piz * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + pix * cos_pitch * sin_yaw));
		d2J_dadz = 2 * niz * (niy * (piz * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) - piy * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + pix * cos_yaw * cos_pitch) - nix * (piy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - piz * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + pix * cos_pitch * sin_yaw));
		d2J_dxdb = nix * (2 * niy * (piz * cos_pitch * cos_roll * sin_yaw - pix * sin_yaw * sin_pitch + piy * cos_pitch * sin_yaw * sin_roll) - 2 * niz * (pix * cos_pitch + piz * cos_roll * sin_pitch + piy * sin_pitch * sin_roll) + 2 * nix * (piz * cos_yaw * cos_pitch * cos_roll - pix * cos_yaw * sin_pitch + piy * cos_yaw * cos_pitch * sin_roll));
		d2J_dbdx = 2 * nix * (niy * (piz * cos_pitch * cos_roll * sin_yaw - pix * sin_yaw * sin_pitch + piy * cos_pitch * sin_yaw * sin_roll) - niz * (pix * cos_pitch + piz * cos_roll * sin_pitch + piy * sin_pitch * sin_roll) + nix * (piz * cos_yaw * cos_pitch * cos_roll - pix * cos_yaw * sin_pitch + piy * cos_yaw * cos_pitch * sin_roll));
		d2J_dydb = niy * (2 * niy * (piz * cos_pitch * cos_roll * sin_yaw - pix * sin_yaw * sin_pitch + piy * cos_pitch * sin_yaw * sin_roll) - 2 * niz * (pix * cos_pitch + piz * cos_roll * sin_pitch + piy * sin_pitch * sin_roll) + 2 * nix * (piz * cos_yaw * cos_pitch * cos_roll - pix * cos_yaw * sin_pitch + piy * cos_yaw * cos_pitch * sin_roll));
		d2J_dbdy = 2 * niy * (niy * (piz * cos_pitch * cos_roll * sin_yaw - pix * sin_yaw * sin_pitch + piy * cos_pitch * sin_yaw * sin_roll) - niz * (pix * cos_pitch + piz * cos_roll * sin_pitch + piy * sin_pitch * sin_roll) + nix * (piz * cos_yaw * cos_pitch * cos_roll - pix * cos_yaw * sin_pitch + piy * cos_yaw * cos_pitch * sin_roll));
		d2J_dzdb = niz * (2 * niy * (piz * cos_pitch * cos_roll * sin_yaw - pix * sin_yaw * sin_pitch + piy * cos_pitch * sin_yaw * sin_roll) - 2 * niz * (pix * cos_pitch + piz * cos_roll * sin_pitch + piy * sin_pitch * sin_roll) + 2 * nix * (piz * cos_yaw * cos_pitch * cos_roll - pix * cos_yaw * sin_pitch + piy * cos_yaw * cos_pitch * sin_roll));
		d2J_dbdz = 2 * niz * (niy * (piz * cos_pitch * cos_roll * sin_yaw - pix * sin_yaw * sin_pitch + piy * cos_pitch * sin_yaw * sin_roll) - niz * (pix * cos_pitch + piz * cos_roll * sin_pitch + piy * sin_pitch * sin_roll) + nix * (piz * cos_yaw * cos_pitch * cos_roll - pix * cos_yaw * sin_pitch + piy * cos_yaw * cos_pitch * sin_roll));
		d2J_dxdc = nix * (2 * nix * (piy * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) + piz * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll)) - 2 * niy * (piy * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + piz * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll)) + 2 * niz * (piy * cos_pitch * cos_roll - piz * cos_pitch * sin_roll));
		d2J_dcdx = 2 * nix * (nix * (piy * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) + piz * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll)) - niy * (piy * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + piz * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll)) + niz * (piy * cos_pitch * cos_roll - piz * cos_pitch * sin_roll));
		d2J_dydc = niy * (2 * nix * (piy * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) + piz * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll)) - 2 * niy * (piy * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + piz * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll)) + 2 * niz * (piy * cos_pitch * cos_roll - piz * cos_pitch * sin_roll));
		d2J_dcdy = 2 * niy * (nix * (piy * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) + piz * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll)) - niy * (piy * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + piz * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll)) + niz * (piy * cos_pitch * cos_roll - piz * cos_pitch * sin_roll));
		d2J_dzdc = niz * (2 * nix * (piy * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) + piz * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll)) - 2 * niy * (piy * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + piz * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll)) + 2 * niz * (piy * cos_pitch * cos_roll - piz * cos_pitch * sin_roll));
		d2J_dcdz = 2 * niz * (nix * (piy * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) + piz * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll)) - niy * (piy * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + piz * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll)) + niz * (piy * cos_pitch * cos_roll - piz * cos_pitch * sin_roll));
		d2J_dadb = (niy * (piz * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) - piy * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + pix * cos_yaw * cos_pitch) - nix * (piy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - piz * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + pix * cos_pitch * sin_yaw)) * (2 * niy * (piz * cos_pitch * cos_roll * sin_yaw - pix * sin_yaw * sin_pitch + piy * cos_pitch * sin_yaw * sin_roll) - 2 * niz * (pix * cos_pitch + piz * cos_roll * sin_pitch + piy * sin_pitch * sin_roll) + 2 * nix * (piz * cos_yaw * cos_pitch * cos_roll - pix * cos_yaw * sin_pitch + piy * cos_yaw * cos_pitch * sin_roll)) - (2 * nix * (piz * cos_pitch * cos_roll * sin_yaw - pix * sin_yaw * sin_pitch + piy * cos_pitch * sin_yaw * sin_roll) - 2 * niy * (piz * cos_yaw * cos_pitch * cos_roll - pix * cos_yaw * sin_pitch + piy * cos_yaw * cos_pitch * sin_roll)) * (nix * (correction_x - qix - piy * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + piz * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) + pix * cos_yaw * cos_pitch) + niy * (correction_y - qiy + piy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - piz * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + pix * cos_pitch * sin_yaw) + niz * (correction_z - qiz - pix * sin_pitch + piz * cos_pitch * cos_roll + piy * cos_pitch * sin_roll));
		d2J_dbda = (2 * niy * (piz * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) - piy * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + pix * cos_yaw * cos_pitch) - 2 * nix * (piy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - piz * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + pix * cos_pitch * sin_yaw)) * (niy * (piz * cos_pitch * cos_roll * sin_yaw - pix * sin_yaw * sin_pitch + piy * cos_pitch * sin_yaw * sin_roll) - niz * (pix * cos_pitch + piz * cos_roll * sin_pitch + piy * sin_pitch * sin_roll) + nix * (piz * cos_yaw * cos_pitch * cos_roll - pix * cos_yaw * sin_pitch + piy * cos_yaw * cos_pitch * sin_roll)) - (2 * nix * (piz * cos_pitch * cos_roll * sin_yaw - pix * sin_yaw * sin_pitch + piy * cos_pitch * sin_yaw * sin_roll) - 2 * niy * (piz * cos_yaw * cos_pitch * cos_roll - pix * cos_yaw * sin_pitch + piy * cos_yaw * cos_pitch * sin_roll)) * (nix * (correction_x - qix - piy * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + piz * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) + pix * cos_yaw * cos_pitch) + niy * (correction_y - qiy + piy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - piz * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + pix * cos_pitch * sin_yaw) + niz * (correction_z - qiz - pix * sin_pitch + piz * cos_pitch * cos_roll + piy * cos_pitch * sin_roll));
		d2J_dbdc = (2 * nix * (piy * cos_yaw * cos_pitch * cos_roll - piz * cos_yaw * cos_pitch * sin_roll) - 2 * niz * (piy * cos_roll * sin_pitch - piz * sin_pitch * sin_roll) + 2 * niy * (piy * cos_pitch * cos_roll * sin_yaw - piz * cos_pitch * sin_yaw * sin_roll)) * (nix * (correction_x - qix - piy * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + piz * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) + pix * cos_yaw * cos_pitch) + niy * (correction_y - qiy + piy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - piz * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + pix * cos_pitch * sin_yaw) + niz * (correction_z - qiz - pix * sin_pitch + piz * cos_pitch * cos_roll + piy * cos_pitch * sin_roll)) + (niy * (piz * cos_pitch * cos_roll * sin_yaw - pix * sin_yaw * sin_pitch + piy * cos_pitch * sin_yaw * sin_roll) - niz * (pix * cos_pitch + piz * cos_roll * sin_pitch + piy * sin_pitch * sin_roll) + nix * (piz * cos_yaw * cos_pitch * cos_roll - pix * cos_yaw * sin_pitch + piy * cos_yaw * cos_pitch * sin_roll)) * (2 * nix * (piy * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) + piz * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll)) - 2 * niy * (piy * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + piz * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll)) + 2 * niz * (piy * cos_pitch * cos_roll - piz * cos_pitch * sin_roll));
		d2J_dcdb = (2 * nix * (piy * cos_yaw * cos_pitch * cos_roll - piz * cos_yaw * cos_pitch * sin_roll) - 2 * niz * (piy * cos_roll * sin_pitch - piz * sin_pitch * sin_roll) + 2 * niy * (piy * cos_pitch * cos_roll * sin_yaw - piz * cos_pitch * sin_yaw * sin_roll)) * (nix * (correction_x - qix - piy * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + piz * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) + pix * cos_yaw * cos_pitch) + niy * (correction_y - qiy + piy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - piz * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + pix * cos_pitch * sin_yaw) + niz * (correction_z - qiz - pix * sin_pitch + piz * cos_pitch * cos_roll + piy * cos_pitch * sin_roll)) + (2 * niy * (piz * cos_pitch * cos_roll * sin_yaw - pix * sin_yaw * sin_pitch + piy * cos_pitch * sin_yaw * sin_roll) - 2 * niz * (pix * cos_pitch + piz * cos_roll * sin_pitch + piy * sin_pitch * sin_roll) + 2 * nix * (piz * cos_yaw * cos_pitch * cos_roll - pix * cos_yaw * sin_pitch + piy * cos_yaw * cos_pitch * sin_roll)) * (nix * (piy * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) + piz * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll)) - niy * (piy * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + piz * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll)) + niz * (piy * cos_pitch * cos_roll - piz * cos_pitch * sin_roll));
		d2J_dcda = (2 * niy * (piz * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) - piy * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + pix * cos_yaw * cos_pitch) - 2 * nix * (piy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - piz * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + pix * cos_pitch * sin_yaw)) * (nix * (piy * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) + piz * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll)) - niy * (piy * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + piz * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll)) + niz * (piy * cos_pitch * cos_roll - piz * cos_pitch * sin_roll)) + (2 * nix * (piy * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + piz * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll)) + 2 * niy * (piy * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) + piz * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll))) * (nix * (correction_x - qix - piy * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + piz * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) + pix * cos_yaw * cos_pitch) + niy * (correction_y - qiy + piy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - piz * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + pix * cos_pitch * sin_yaw) + niz * (correction_z - qiz - pix * sin_pitch + piz * cos_pitch * cos_roll + piy * cos_pitch * sin_roll));
		d2J_dadc = (niy * (piz * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) - piy * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + pix * cos_yaw * cos_pitch) - nix * (piy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - piz * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + pix * cos_pitch * sin_yaw)) * (2 * nix * (piy * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) + piz * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll)) - 2 * niy * (piy * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + piz * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll)) + 2 * niz * (piy * cos_pitch * cos_roll - piz * cos_pitch * sin_roll)) + (2 * nix * (piy * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + piz * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll)) + 2 * niy * (piy * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) + piz * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll))) * (nix * (correction_x - qix - piy * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + piz * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) + pix * cos_yaw * cos_pitch) + niy * (correction_y - qiy + piy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - piz * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + pix * cos_pitch * sin_yaw) + niz * (correction_z - qiz - pix * sin_pitch + piz * cos_pitch * cos_roll + piy * cos_pitch * sin_roll));

		Eigen::MatrixXd d2J_dX2_temp(6, 6);
		d2J_dX2_temp << d2J_dx2, d2J_dydx, d2J_dzdx, d2J_dadx, d2J_dbdx, d2J_dzdx, d2J_dxdy, d2J_dy2, d2J_dzdy, d2J_dady, d2J_dbdy, d2J_dcdy, d2J_dxdz, d2J_dydz, d2J_dz2, d2J_dadz, d2J_dbdz, d2J_dcdz, d2J_dxda, d2J_dyda, d2J_dzda, d2J_da2, d2J_dbda, d2J_dcda, d2J_dxdb, d2J_dydb, d2J_dzdb, d2J_dadb, d2J_db2, d2J_dcdb, d2J_dxdc, d2J_dydc, d2J_dzdc, d2J_dadc, d2J_dbdc, d2J_dc2;
		d2J_dX2 = d2J_dX2 + d2J_dX2_temp;
	}

	Eigen::MatrixXd d2J_dZdX(6, 6 * ambient_cloud_orrespondences_size);
	for (int k = 0; k < ambient_cloud_orrespondences_size; ++k) {
		double pix = ambient_cloud_orrespondences.points[k].x;
		double piy = ambient_cloud_orrespondences.points[k].y;
		double piz = ambient_cloud_orrespondences.points[k].z;
		double qix = reference_cloud_correspondences.points[k].x;
		double qiy = reference_cloud_correspondences.points[k].y;
		double qiz = reference_cloud_correspondences.points[k].z;

		double nix = reference_cloud_correspondences[k].normal_x;
		double niy = reference_cloud_correspondences[k].normal_y;
		double niz = reference_cloud_correspondences[k].normal_z;

		Eigen::MatrixXd d2J_dZdX_temp(6, 6);
		double d2J_dpix_dx, d2J_dpiy_dx, d2J_dpiz_dx, d2J_dqix_dx, d2J_dqiy_dx, d2J_dqiz_dx, d2J_dpix_dy, d2J_dpiy_dy, d2J_dpiz_dy, d2J_dqix_dy, d2J_dqiy_dy, d2J_dqiz_dy, d2J_dpix_dz, d2J_dpiy_dz, d2J_dpiz_dz, d2J_dqix_dz, d2J_dqiy_dz, d2J_dqiz_dz, d2J_dpix_da, d2J_dpiy_da, d2J_dpiz_da, d2J_dqix_da, d2J_dqiy_da, d2J_dqiz_da, d2J_dpix_db, d2J_dpiy_db, d2J_dpiz_db, d2J_dqix_db, d2J_dqiy_db, d2J_dqiz_db, d2J_dpix_dc, d2J_dpiy_dc, d2J_dpiz_dc, d2J_dqix_dc, d2J_dqiy_dc, d2J_dqiz_dc;
		d2J_dpix_dx = 2 * nix * (nix * cos_yaw * cos_pitch - niz * sin_pitch + niy * cos_pitch * sin_yaw);
		d2J_dpix_dy = 2 * niy * (nix * cos_yaw * cos_pitch - niz * sin_pitch + niy * cos_pitch * sin_yaw);
		d2J_dpix_dz = 2 * niz * (nix * cos_yaw * cos_pitch - niz * sin_pitch + niy * cos_pitch * sin_yaw);
		d2J_dpix_da = (2 * niy * cos_yaw * cos_pitch - 2 * nix * cos_pitch * sin_yaw) * (nix * (correction_x - qix - piy * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + piz * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) + pix * cos_yaw * cos_pitch) + niy * (correction_y - qiy + piy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - piz * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + pix * cos_pitch * sin_yaw) + niz * (correction_z - qiz - pix * sin_pitch + piz * cos_pitch * cos_roll + piy * cos_pitch * sin_roll)) + (2 * niy * (piz * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) - piy * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + pix * cos_yaw * cos_pitch) - 2 * nix * (piy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - piz * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + pix * cos_pitch * sin_yaw)) * (nix * cos_yaw * cos_pitch - niz * sin_pitch + niy * cos_pitch * sin_yaw);
		d2J_dpix_db = (2 * niy * (piz * cos_pitch * cos_roll * sin_yaw - pix * sin_yaw * sin_pitch + piy * cos_pitch * sin_yaw * sin_roll) - 2 * niz * (pix * cos_pitch + piz * cos_roll * sin_pitch + piy * sin_pitch * sin_roll) + 2 * nix * (piz * cos_yaw * cos_pitch * cos_roll - pix * cos_yaw * sin_pitch + piy * cos_yaw * cos_pitch * sin_roll)) * (nix * cos_yaw * cos_pitch - niz * sin_pitch + niy * cos_pitch * sin_yaw) - (2 * niz * cos_pitch + 2 * nix * cos_yaw * sin_pitch + 2 * niy * sin_yaw * sin_pitch) * (nix * (correction_x - qix - piy * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + piz * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) + pix * cos_yaw * cos_pitch) + niy * (correction_y - qiy + piy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - piz * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + pix * cos_pitch * sin_yaw) + niz * (correction_z - qiz - pix * sin_pitch + piz * cos_pitch * cos_roll + piy * cos_pitch * sin_roll));
		d2J_dpix_dc = (2 * nix * (piy * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) + piz * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll)) - 2 * niy * (piy * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + piz * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll)) + 2 * niz * (piy * cos_pitch * cos_roll - piz * cos_pitch * sin_roll)) * (nix * cos_yaw * cos_pitch - niz * sin_pitch + niy * cos_pitch * sin_yaw);
		d2J_dpiy_dx = 2 * nix * (niy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - nix * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + niz * cos_pitch * sin_roll);
		d2J_dpiy_dy = 2 * niy * (niy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - nix * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + niz * cos_pitch * sin_roll);
		d2J_dpiy_dz = 2 * niz * (niy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - nix * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + niz * cos_pitch * sin_roll);
		d2J_dpiy_da = (2 * niy * (piz * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) - piy * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + pix * cos_yaw * cos_pitch) - 2 * nix * (piy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - piz * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + pix * cos_pitch * sin_yaw)) * (niy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - nix * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + niz * cos_pitch * sin_roll) - (2 * nix * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) + 2 * niy * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll)) * (nix * (correction_x - qix - piy * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + piz * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) + pix * cos_yaw * cos_pitch) + niy * (correction_y - qiy + piy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - piz * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + pix * cos_pitch * sin_yaw) + niz * (correction_z - qiz - pix * sin_pitch + piz * cos_pitch * cos_roll + piy * cos_pitch * sin_roll));
		d2J_dpiy_db = (2 * niy * (piz * cos_pitch * cos_roll * sin_yaw - pix * sin_yaw * sin_pitch + piy * cos_pitch * sin_yaw * sin_roll) - 2 * niz * (pix * cos_pitch + piz * cos_roll * sin_pitch + piy * sin_pitch * sin_roll) + 2 * nix * (piz * cos_yaw * cos_pitch * cos_roll - pix * cos_yaw * sin_pitch + piy * cos_yaw * cos_pitch * sin_roll)) * (niy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - nix * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + niz * cos_pitch * sin_roll) + (2 * nix * cos_yaw * cos_pitch * sin_roll - 2 * niz * sin_pitch * sin_roll + 2 * niy * cos_pitch * sin_yaw * sin_roll) * (nix * (correction_x - qix - piy * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + piz * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) + pix * cos_yaw * cos_pitch) + niy * (correction_y - qiy + piy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - piz * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + pix * cos_pitch * sin_yaw) + niz * (correction_z - qiz - pix * sin_pitch + piz * cos_pitch * cos_roll + piy * cos_pitch * sin_roll));
		d2J_dpiy_dc = (2 * nix * (piy * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) + piz * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll)) - 2 * niy * (piy * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + piz * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll)) + 2 * niz * (piy * cos_pitch * cos_roll - piz * cos_pitch * sin_roll)) * (niy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - nix * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + niz * cos_pitch * sin_roll) + (2 * nix * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) - 2 * niy * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + 2 * niz * cos_pitch * cos_roll) * (nix * (correction_x - qix - piy * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + piz * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) + pix * cos_yaw * cos_pitch) + niy * (correction_y - qiy + piy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - piz * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + pix * cos_pitch * sin_yaw) + niz * (correction_z - qiz - pix * sin_pitch + piz * cos_pitch * cos_roll + piy * cos_pitch * sin_roll));
		d2J_dpiz_dx = 2 * nix * (nix * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) - niy * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + niz * cos_pitch * cos_roll);
		d2J_dpiz_dy = 2 * niy * (nix * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) - niy * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + niz * cos_pitch * cos_roll);
		d2J_dpiz_dz = 2 * niz * (nix * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) - niy * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + niz * cos_pitch * cos_roll);
		d2J_dpiz_da = (2 * niy * (piz * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) - piy * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + pix * cos_yaw * cos_pitch) - 2 * nix * (piy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - piz * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + pix * cos_pitch * sin_yaw)) * (nix * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) - niy * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + niz * cos_pitch * cos_roll) + (2 * nix * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + 2 * niy * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch)) * (nix * (correction_x - qix - piy * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + piz * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) + pix * cos_yaw * cos_pitch) + niy * (correction_y - qiy + piy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - piz * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + pix * cos_pitch * sin_yaw) + niz * (correction_z - qiz - pix * sin_pitch + piz * cos_pitch * cos_roll + piy * cos_pitch * sin_roll));
		d2J_dpiz_db = (2 * niy * (piz * cos_pitch * cos_roll * sin_yaw - pix * sin_yaw * sin_pitch + piy * cos_pitch * sin_yaw * sin_roll) - 2 * niz * (pix * cos_pitch + piz * cos_roll * sin_pitch + piy * sin_pitch * sin_roll) + 2 * nix * (piz * cos_yaw * cos_pitch * cos_roll - pix * cos_yaw * sin_pitch + piy * cos_yaw * cos_pitch * sin_roll)) * (nix * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) - niy * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + niz * cos_pitch * cos_roll) + (2 * nix * cos_yaw * cos_pitch * cos_roll - 2 * niz * cos_roll * sin_pitch + 2 * niy * cos_pitch * cos_roll * sin_yaw) * (nix * (correction_x - qix - piy * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + piz * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) + pix * cos_yaw * cos_pitch) + niy * (correction_y - qiy + piy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - piz * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + pix * cos_pitch * sin_yaw) + niz * (correction_z - qiz - pix * sin_pitch + piz * cos_pitch * cos_roll + piy * cos_pitch * sin_roll));
		d2J_dpiz_dc = (2 * nix * (piy * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) + piz * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll)) - 2 * niy * (piy * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + piz * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll)) + 2 * niz * (piy * cos_pitch * cos_roll - piz * cos_pitch * sin_roll)) * (nix * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) - niy * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + niz * cos_pitch * cos_roll) - (2 * niy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - 2 * nix * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + 2 * niz * cos_pitch * sin_roll) * (nix * (correction_x - qix - piy * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + piz * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) + pix * cos_yaw * cos_pitch) + niy * (correction_y - qiy + piy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - piz * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + pix * cos_pitch * sin_yaw) + niz * (correction_z - qiz - pix * sin_pitch + piz * cos_pitch * cos_roll + piy * cos_pitch * sin_roll));
		d2J_dqix_dx = -2 * pow(nix, 2);
		d2J_dqix_dy = -2 * nix * niy;
		d2J_dqix_dz = -2 * nix * niz;
		d2J_dqix_da = -nix * (2 * niy * (piz * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) - piy * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + pix * cos_yaw * cos_pitch) - 2 * nix * (piy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - piz * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + pix * cos_pitch * sin_yaw));
		d2J_dqix_db = -nix * (2 * niy * (piz * cos_pitch * cos_roll * sin_yaw - pix * sin_yaw * sin_pitch + piy * cos_pitch * sin_yaw * sin_roll) - 2 * niz * (pix * cos_pitch + piz * cos_roll * sin_pitch + piy * sin_pitch * sin_roll) + 2 * nix * (piz * cos_yaw * cos_pitch * cos_roll - pix * cos_yaw * sin_pitch + piy * cos_yaw * cos_pitch * sin_roll));
		d2J_dqix_dc = -nix * (2 * nix * (piy * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) + piz * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll)) - 2 * niy * (piy * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + piz * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll)) + 2 * niz * (piy * cos_pitch * cos_roll - piz * cos_pitch * sin_roll));
		d2J_dqiy_dx = -2 * nix * niy;
		d2J_dqiy_dy = -2 * pow(niy, 2);
		d2J_dqiy_dz = -2 * niy * niz;
		d2J_dqiy_da = -niy * (2 * niy * (piz * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) - piy * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + pix * cos_yaw * cos_pitch) - 2 * nix * (piy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - piz * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + pix * cos_pitch * sin_yaw));
		d2J_dqiy_db = -niy * (2 * niy * (piz * cos_pitch * cos_roll * sin_yaw - pix * sin_yaw * sin_pitch + piy * cos_pitch * sin_yaw * sin_roll) - 2 * niz * (pix * cos_pitch + piz * cos_roll * sin_pitch + piy * sin_pitch * sin_roll) + 2 * nix * (piz * cos_yaw * cos_pitch * cos_roll - pix * cos_yaw * sin_pitch + piy * cos_yaw * cos_pitch * sin_roll));
		d2J_dqiy_dc = -niy * (2 * nix * (piy * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) + piz * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll)) - 2 * niy * (piy * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + piz * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll)) + 2 * niz * (piy * cos_pitch * cos_roll - piz * cos_pitch * sin_roll));
		d2J_dqiz_dx = -2 * nix * niz;
		d2J_dqiz_dy = -2 * niy * niz;
		d2J_dqiz_dz = -2 * pow(niz, 2);
		d2J_dqiz_da = -niz * (2 * niy * (piz * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) - piy * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll) + pix * cos_yaw * cos_pitch) - 2 * nix * (piy * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll) - piz * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + pix * cos_pitch * sin_yaw));
		d2J_dqiz_db = -niz * (2 * niy * (piz * cos_pitch * cos_roll * sin_yaw - pix * sin_yaw * sin_pitch + piy * cos_pitch * sin_yaw * sin_roll) - 2 * niz * (pix * cos_pitch + piz * cos_roll * sin_pitch + piy * sin_pitch * sin_roll) + 2 * nix * (piz * cos_yaw * cos_pitch * cos_roll - pix * cos_yaw * sin_pitch + piy * cos_yaw * cos_pitch * sin_roll));
		d2J_dqiz_dc =-niz * (2 * nix * (piy * (sin_yaw * sin_roll + cos_yaw * cos_roll * sin_pitch) + piz * (cos_roll * sin_yaw - cos_yaw * sin_pitch * sin_roll)) - 2 * niy * (piy * (cos_yaw * sin_roll - cos_roll * sin_yaw * sin_pitch) + piz * (cos_yaw * cos_roll + sin_yaw * sin_pitch * sin_roll)) + 2 * niz * (piy * cos_pitch * cos_roll - piz * cos_pitch * sin_roll));
		d2J_dZdX_temp << d2J_dpix_dx, d2J_dpiy_dx, d2J_dpiz_dx, d2J_dqix_dx, d2J_dqiy_dx, d2J_dqiz_dx, d2J_dpix_dy, d2J_dpiy_dy, d2J_dpiz_dy, d2J_dqix_dy, d2J_dqiy_dy, d2J_dqiz_dy, d2J_dpix_dz, d2J_dpiy_dz, d2J_dpiz_dz, d2J_dqix_dz, d2J_dqiy_dz, d2J_dqiz_dz, d2J_dpix_da, d2J_dpiy_da, d2J_dpiz_da, d2J_dqix_da, d2J_dqiy_da, d2J_dqiz_da, d2J_dpix_db, d2J_dpiy_db, d2J_dpiz_db, d2J_dqix_db, d2J_dqiy_db, d2J_dqiz_db, d2J_dpix_dc, d2J_dpiy_dc, d2J_dpiz_dc, d2J_dqix_dc, d2J_dqiy_dc, d2J_dqiz_dc;
		d2J_dZdX.block<6, 6>(0, 6 * k) = d2J_dZdX_temp;
	}

	Eigen::MatrixXd cov_z(6 * ambient_cloud_orrespondences_size, 6 * ambient_cloud_orrespondences_size);
	cov_z = sensor_std_dev_noise * sensor_std_dev_noise * Eigen::MatrixXd::Identity(6 * ambient_cloud_orrespondences_size, 6 * ambient_cloud_orrespondences_size);
	Eigen::FullPivLU<Eigen::MatrixXd> lu(d2J_dX2);
	Eigen::MatrixXd d2J_dX2_inverse = lu.inverse();
	covariance_out = d2J_dX2_inverse * d2J_dZdX * cov_z * d2J_dZdX.transpose() * d2J_dX2_inverse;

	return true;
}

// >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>   </RegistrationCovariancePointToPlane3D-functions>  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
// =============================================================================  </public-section>  ===========================================================================

// =============================================================================   <protected-section>   =======================================================================
// =============================================================================   </protected-section>  =======================================================================

// >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>   <template instantiations>   <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
// >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>   </template instantiations>  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

} /* namespace dynamic_robot_localization */
